---
title: "AnalysisExample_HK"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(skimr)
library(modelr)
library(stringr)
library(corrplot)
library(RColorBrewer)
library("PerformanceAnalytics")
library("Hmisc")
library(Rmisc)
library(lubridate)
library(ggbeeswarm)
library(GGally)
library(effsize)
library(magrittr)


flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

```

## BCI - SoANEW and SoO project analysis
First we need to import all data so we can connect(merge) it

```{r questionnaire, echo=FALSE}
questionnaire <- as_tibble(read.csv(file.path("./","questionnaire.csv"), fileEncoding="UTF-8-BOM"))

orderNumber<-rep(c(1,2,2,1),11)
questionnaire<-cbind(questionnaire,orderNumber)
#cleaning up your data to make it merge friendly
mood <- as_tibble(read.csv(file.path("./","Mood.csv"),stringsAsFactors=FALSE, fileEncoding="UTF-8-BOM")) %>% mutate_if(is.character, stringr::str_replace_all, pattern = " ", replacement = "_")


  #feel free to break down this long command (run it with only the first lines and see how each additional pipe %>% changes the data)
mood <- mood %>%
  pivot_longer(cols = -X, names_to = "Participant") %>%  
  mutate_if(is.character, stringr::str_replace_all, pattern = " ", replacement = "_") %>%
  mutate_if(is.character, stringr::str_replace_all, pattern = "P", replacement = "") %>%
  mutate(Participant = as.numeric(Participant)) %>%
  pivot_wider(names_from = X)


#Q1 I look forward to work with the BCI (brain-computer interface)	
#Q2 I think I can deal with the difficulties of the BCI        		
#Q3 I do not think I will do well		                                             
#Q4 I feel pressured to perform well						
#Q5 BCI is a big challenge for me		            			
#Q6 I look forward to work with the BCI					
#Q7 I am very curious how I will perform					
#Q8 I dread that I can embarrass myself					
#Q9 I am fully determined to give it my best				
#Q10 I don’t need a reward for participating, I can have fun without	
#Q11 It’s embarrassing for me to fail						
#Q12 I think that everyone can control their brain activity		
#Q13 I think I won’t be able to accomplish BCI task today		
#Q14 When I do well in the BCI, I will be proud of my achievement	

```
 
```{r logData, echo=FALSE,message=F, warning=F,results='hide'}
 
 #main game event data
 # df <-    list.files(recursive=TRUE ,path = "./data",
 #                    pattern = "*Game.csv", 
 #                    full.names = T) %>% 
 #  tibble(filename = .) %>%   
 #  mutate(file_contents = map(filename,~ read_csv(file.path(.),na = "NULL")))  %>% 
 #  unnest(cols=-filename) %>% 
 #  separate(col=filename,sep="/",into=c("start","folder","Participant","Level","filename")) %>%
 #  mutate(Participant=as.numeric(str_replace(Participant,"P","")), Level=as.factor(Level))

 # make timestamps more easily usable - express as seconds, set markers when input windows attempts start/end
 # df <- df %>%
 #  dplyr::group_by(Participant, Level) %>%
 #   mutate(
 #    vis_t_time = as.POSIXlt(Timestamp, format = "%Y-%m-%d %H:%M:%OS"),
 #    timeInSecs = seconds(vis_t_time),
 #    GameIsOn = ifelse(Event == "GameRunning", 1, 0),
 #    GameIsOn = cumsum(GameIsOn)) %>%
 #    arrange(Participant,Level,timeInSecs) %>%
 #    dplyr::mutate(InputWindowNum = dplyr::lag(ifelse(Event == "GameDecision", 1, 0),default=0)) %>%
 #    dplyr::mutate(InputWindowNum = cumsum(InputWindowNum)) %>%
 #    ungroup()
 # 
 # df<- df  %>% group_by(Participant, Level) %>% dplyr::summarise(StartTime=min(timeInSecs)) %>% dplyr::right_join(df)
   
# #get times for each input windows
# df <- df %>%
#   select(Participant, Level, InputWindowNum,timeInSecs) %>%
#   dplyr::group_by(Participant, Level, InputWindowNum) %>%
#   dplyr::summarise(startTime = min(timeInSecs)) %>%
#   right_join(df) %>%
#   mutate(timeSinceIWstart = ifelse(TrialResult == "AccInput",timeInSecs - startTime,NA))
  
# 
# dfSummary <- df %>%
#   dplyr::mutate(successes=ifelse(TrialResult == "AccInput", 1, 0))%>%
#   dplyr::group_by(Participant, Level) %>%
#   # select(Participant, Level, InputWindowNum, timeSinceIWstart, TrialResult) %>%
#   dplyr::summarize(Performance = sum(successes,na.rm = TRUE) / max(InputWindowNum), 
#                           activateDelay = mean(timeSinceIWstart,na.rm = TRUE))

```
OK next data (code is identical apart from the file name patter)
```{r logMeta Data, echo=FALSE,message=F, warning=F,results='hide'}
#   
# dm <-     list.files(recursive=T,path = "./data",
#                      pattern = "*Meta.csv", 
#                      full.names = T) %>% 
#   tibble(filename = .) %>%   
#   mutate(file_contents = map(filename,~ read_csv(file.path(.),na = "NULL")))  %>% 
#   unnest(cols=-filename)%>% 
#   separate(col=filename,sep="/",into=c("start","folder","Participant","Level","filename")) %>%
#   mutate(Participant=as.numeric(str_replace(Participant,"P","")))
```
Sample  data next (code is identical apart from the file name patter)
```{r logSampleData, echo=FALSE,message=F, warning=F,results='hide'}
 
# ds <- list.files(recursive=T,path = "./data",
#               pattern = "*Sample.csv", 
#               full.names = T) %>% 
#   tibble(filename = .) %>%   
#   mutate(file_contents = map(filename,~ read_csv(file.path(.),na = "NULL")))  %>% 
#   unnest(cols=-filename)%>% 
#   separate(col=filename,sep="/",into=c("start","folder","Participant","Level","filename"))
 
```

## Initial analysis
```{r theBigMerge}
# dfSummary <-dfSummary %>% merge(questionnaire) %>% merge(mood) 
# dfSummary <-merge(dfSummary,questionnaire)
# 
# dfSummary %>%
#   select(-Participant) %>%
#   group_by(Level) %>%
#   skim()
# 
# dfMainVarsSummary <- dfSummary %>%
#   select(Level:Performance) %>%
#   pivot_longer(cols = -Level, names_to = "measure", values_to = "val") %>%
#   dplyr::group_by(Level, measure) %>%
#   dplyr::summarize(mean = round(mean(val),1),
#                    sd=round(sd(val),1)) %>%
#   filter(!(measure=="orderNumber")) %>%
#   pivot_wider(names_from = measure, values_from = c(mean,sd))

```

Overview
```{r pressure}
# questionnaire %>%
#   select(-Participant) %>%
#   group_by(Level) %>%
#   skim()

dfSummary <- questionnaire %>% merge(questionnaire) %>% merge(mood)
dfSummary %>%
  select(-Participant) %>%
  group_by(Level) %>%
  skim()
```

Correlation overview (you really need to reduce/collapse your Mood questionnaire )

```{r correlationStuff}
# check out this web page on easy summaries for correlations:
#http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software
drop <- "Level"
df = dfSummary[,!(names(dfSummary) %in% drop)]
chart.Correlation(df[,-c(1,2,9:21)], histogram=TRUE, pch=19)


res2 <- Hmisc::rcorr(as.matrix(df[,-c(1,2,9:21)]))
flattenCorrMatrix(res2$r, res2$P)

corrplot(cor(df[dfSummary$Level=="Body",-c(1,2)]), type="upper",col=brewer.pal(n=8, name="RdYlBu"))
corrplot(cor(df[dfSummary$Level=="Blocks",-c(1,2)]), type="upper",col=brewer.pal(n=8, name="RdYlBu"))
ggparcoord(df)

dfSummary %>%
  filter(SoANEW > 2) %>%
  ggplot(aes(x = SoANEW, y = SoO, colour = Level)) +
  geom_jitter() +
  geom_smooth(method = "lm", fill = NA)


```
```{r PredictingFrustration}
options(pillar.sigfig = 5)
# broom::tidy(lm(Frustration~Level*(SoANEW+SoO+Performance+activateDelay),data=dfSummary))
# broom::tidy(lm(Frustration~SoANEW+SoO+Performance+activateDelay,data=dfSummary))
broom::tidy(lm(Frustration~Level,data=dfSummary)) %>%mutate_if(is.numeric, round, 5)
broom::tidy(lm(Frustration~Level*orderNumber,data=dfSummary))
broom::tidy(lm(Frustration~SoANEW+Performance,data=dfSummary))
broom::tidy(lm(SoO~Level*orderNumber,data=dfSummary))
broom::tidy(lm(SoANEW~Level*orderNumber,data=dfSummary))
broom::tidy(lm(SoANEW~Level*Performance,data=dfSummary))
broom::tidy(lm(Proprioception~orderNumber,data=dfSummary))
broom::tidy(lm(SoO~Level,data=dfSummary))

broom::tidy(lm(SoANEW~SoO+Performance, data = questionnaire))
broom::tidy(lm(SoANEW~SoO*Performance, data = questionnaire))

broom::tidy(lm(SoAOLD~SoO+Performance, data = questionnaire))
broom::tidy(lm(SoAOLD~SoO*Performance, data = questionnaire))

broom::tidy(lm(Frustration~SoANEW+Performance, data = questionnaire))
broom::tidy(lm(Frustration~SoANEW*Performance, data = questionnaire))

broom::tidy(lm(SoO~Performance, data = questionnaire))
broom::tidy(lm(Performance~SoO, data = questionnaire))

broom::tidy(lm(Performance~SoO+Level, data = questionnaire))
broom::tidy(lm(SoO~Performance+Level, data = questionnaire))

broom::tidy(lm(SoO~SoANEW*Level,data=dfSummary)) %>% mutate_if(is.numeric, round, 5)
options(scipen = 999)
broom::tidy(lm(SoANEW~Performance*Level*orderNumber,data=dfSummary)) %>% mutate_if(is.numeric, round, 5)
options(digits = 3, scipen = -2)


```

```{r PredictingSoANEW}
broom::tidy(lm(SoANEW~SoO,data=dfSummary[dfSummary$Level=='Body',]))
broom::tidy(lm(SoANEW~SoO,data=dfSummary[dfSummary$Level=='Blocks',]))
broom::tidy(lm(SoANEW~SoO*Level,data=dfSummary))

```

```{r Checking the effect of performance on SoANEW, SoO, Frustration and Proprioception}
# There seems to be a small effect(-0.3724182)(S = 10664, p-value = 0.0253) on frustration using Spearsman Rho 
tidy(cor.test(dfSummary$Performance, dfSummary$SoANEW, method="spearman"))

tidy(cor.test(dfSummary$Performance, dfSummary$SoO, method="spearman"))
tidy(cor.test(dfSummary$Performance, dfSummary$Frustration, method="spearman"))
ggplot(dfSummary, aes(x=Performance,y=Frustration, colour=Level)) + geom_point() + geom_smooth(method = "lm", fill = NA)
tidy(cor.test(dfSummary$Performance, dfSummary$Proprioception, method="spearman"))

dfSummary %>% 
  group_by(Level) %>%
  do(tidy(cor.test(.$Performance, .$SoANEW)))

tidy(lm(SoANEW~Level*Performance,data=dfSummary))
plot(dfSummary$Performance,dfSummary$SoANEW)
```
```{r Changing Body to avatar}
class(dfSummary$Level)
dfDataTep <- dfSummary%>%mutate(Level=recode(Level, Body="Avatar"))
dfData <- with(dfDataTep, dfDataTep[order(Level,decreasing = TRUE),])

# dfSummary <- dfSummary %>% mutate(SoOHigh=ifelse(SoO > 3.5, TRUE, FALSE)) # This is a TODO, 3.5 was chosen arbitrarily

#effect size of Hand/block
cliff.delta(dfSummary[dfSummary$Level=='Body',]$SoO,dfSummary[dfSummary$Level=='Blocks',]$SoO,return.dm=TRUE)

```

```{r Counter-balancing mood test}
#non-parametric data


 # dfData %>%
 #  select(Participant, orderNumber,Level, Q1:Q14) %>%
 #  pivot_longer(cols = -c(Level, Participant,orderNumber)) %>%
 #  filter(orderNumber==1) %>% 
 #  group_by(name) %>% 
 #  summarise(p=wilcox.test(value~Level,paired=FALSE,exact=FALSE)$p.value) %>%View()
 
```

```{r Counter-balancing levels and performance}
#parametric data
 ParticipantOrder1 <- dfData %>% filter(orderNumber == 1)
 Avatar1 <- ParticipantOrder1 %>% filter(Level=="Avatar")
 Blocks1 <- ParticipantOrder1 %>% filter(Level=="Blocks")
 ParticipantOrder2 <- dfData %>% filter(orderNumber == 2)
Avatar2 <- ParticipantOrder2 %>% filter(Level=="Avatar")
Blocks2 <- ParticipantOrder2 %>% filter(Level=="Blocks")
#Histograms 
# qplot(Avatar1$Performance,
#       geom="histogram",
#       bins = 50, 
#       main = "Performance as Percentages in Avatar 1",
#       xlim = c(0, 1),
#       ylim = c(0, 3),
#       xlab = "Avatar performance")
# 
# 
# qplot(Blocks1$Performance,
#       geom="histogram",
#       bins = 50,
#       xlim = c(0, 1),
#       ylim = c(0, 3),
#       main = "Performance as Percentages in Blocks 1", 
#       xlab = "Blocks performance")

#ordernumber 1
#Use ParticipantOrder1 and Body,Blocks1
#Check for normality(Shapiro Wilks Test)
#The data is normal if the p-value is above 0.05.
SWTestAvatar1 <- shapiro.test(Avatar1$Performance)
SWTestBlocks1 <- shapiro.test(Blocks1$Performance)
#homogeneity of variance
#leveneTestorder1 <- leveneTest(ParticipantOrder1$Performance,group = ParticipantOrder1$Level, center = "median", data = ParticipantOrder1)
#T test Welch's t-test (Does not require variance check)
t.test(Avatar1$Performance, Blocks1$Performance)
#ordernumber 2

#parametric data
#Histograms
# qplot(Avatar2$Performance,
#       geom="histogram",
#       bins = 50,
#       xlim = c(0, 1),
#       ylim = c(0, 3),
#       main = "Performance as Percentages in Avatar 2", 
#       xlab = "Avatar performance")
# 
# qplot(Blocks2$Performance,
#       geom="histogram",
#       bins = 50,
#       xlim = c(0, 1),
#       ylim = c(0, 3),
#       main = "Performance as Percentages in Blocks 2", 
#       xlab = "Blocks performance")

#Check for normality(Shapiro Wilks Test)
SWTestAvatar2 <- shapiro.test(Avatar2$Performance)
SWTestBlocks2 <- shapiro.test(Blocks2$Performance)
#homogeneity of variance
#leveneTestorder2 <- leveneTest(ParticipantOrder2$Performance,group = ParticipantOrder2$Level, center = "median", data = ParticipantOrder2)
#T test Welch's t-test (Does not require variance check)
t.test(Avatar2$Performance, Blocks2$Performance)

#Check for normality(Shapiro Wilks Test)
shapiro.test(ParticipantOrder1$Performance)
shapiro.test(ParticipantOrder2$Performance)
#T test Welch's t-test (Does not require variance check)
t.test(ParticipantOrder1$Performance, ParticipantOrder2$Performance)


#Check for normality(Shapiro Wilks Test)
shapiro.test(ParticipantOrder1$Performance)
shapiro.test(ParticipantOrder2$Performance)
#T test Welch's t-test (Does not require variance check)
t.test(ParticipantOrder1$Performance, ParticipantOrder2$Performance)

#t.test(dfAvatar$Performance, dfBlocks$Performance)
```

```{r More t-tests}
dfAvatar<- questionnaire %>% filter(Level == "Body")
dfBlocks <- questionnaire %>% filter(Level == "Blocks")

#Check for normality(Shapiro Wilks Test)
shapiro.test(dfAvatar$Performance)
shapiro.test(dfBlocks$Performance)
#T test Welch's t-test (Does not require variance check)
t.test(dfAvatar$Performance, dfBlocks$Performance)

```

```{r Correlation test within ordernumber for SoO on all measurements}
#non-parametric data
#correlation test on measurement within ordernumbers

#tidy(cor.test(lvl1.SoO, lvl1.SoANEW)
tidy(cor.test(ParticipantOrder1$SoO, ParticipantOrder1$SoANEW, method="spearman", exact = FALSE))
#tidy(cor.test(lvl2.SoO, lvl2.SoANEW)
tidy(cor.test(ParticipantOrder2$SoO, ParticipantOrder2$SoANEW, method="spearman", exact = FALSE))
#tidy(cor.test(lvl1.SoO, lvl1.proprioception)
tidy(cor.test(ParticipantOrder1$SoO, ParticipantOrder1$Proprioception, method="spearman", exact = FALSE))
#tidy(cor.test(lvl2.SoO, lvl2.proprioception)
tidy(cor.test(ParticipantOrder2$SoO, ParticipantOrder2$Proprioception, method="spearman", exact = FALSE))
#tidy(cor.test(lvl1.SoO, lvl1.frustration)
tidy(cor.test(ParticipantOrder1$SoO, ParticipantOrder1$Frustration, method="spearman", exact = FALSE))
#tidy(cor.test(lvl2.SoO, lvl2.frustration)
tidy(cor.test(ParticipantOrder2$SoO, ParticipantOrder2$Frustration, method="spearman", exact = FALSE))

```

```{r Correlation test within conditions}
 Avatar <- dfData %>% filter(Level=="Avatar")
 Blocks <- dfData %>% filter(Level=="Blocks")
#cor.test for Avatar SoANEW and SoO
tidy(cor.test(Avatar$SoANEW, Avatar$SoO ,method="spearman", exact = FALSE))
#cor.test for Blocks SoANEW and SoO
tidy(cor.test(Blocks$SoANEW, Blocks$SoO ,method="spearman", exact = FALSE))
#cor.test for Avatar SoANEW and propriception
tidy(cor.test(Avatar$SoANEW, Avatar$Proprioception ,method="spearman", exact = FALSE))
#cor.test for Blocks SoANEW and proprioception
tidy(cor.test(Blocks$SoANEW, Blocks$Proprioception ,method="spearman", exact = FALSE))
#cor.test for Avatar perf. and prop.
tidy(cor.test(Avatar$Performance, Avatar$Proprioception ,method="spearman", exact = FALSE))
#cor.test for Blocks perf. and prop.
tidy(cor.test(Blocks$Performance, Blocks$Proprioception ,method="spearman", exact = FALSE))

tidy(cor.test(dfBlocks$Performance, dfBlocks$SoO ,method="spearman", exact = FALSE))
tidy(cor.test(dfAvatar$Performance, dfAvatar$SoO ,method="spearman", exact = FALSE))
```

```{r Correlation test for SoO all measurements}
#correlation test on SoANEW
tidy(cor.test(dfData$SoO, dfData$SoANEW, method="spearman", exact = FALSE))
SoOSoANEWScatter <- ggplot(dfData,aes(x=SoO,y=SoANEW, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoO") +
  ylab(label = "SoANEW") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)

tidy(cor.test(questionnaire$SoO, questionnaire$SoANEW, method="spearman", exact = FALSE))
CorrbetweenNEWSoANEWandsoo <- ggplot(questionnaire,aes(x=SoO,y=SoANEW, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoO") +
  ylab(label = "New Agency Measure") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("CorrbetweenNEWSoANEWandsoo.png", width = 800, height = 600)
plot(CorrbetweenNEWSoANEWandsoo)
dev.off()

tidy(cor.test(questionnaire$SoO, questionnaire$SoAOLD, method="spearman", exact = FALSE))
CorrbetweenOLDSoANEWandsoo <- ggplot(questionnaire,aes(x=SoO,y=SoAOLD, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoO") +
  ylab(label = "Old Agency Measure") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("CorrbetweenOLDSoANEWandsoo.png", width = 800, height = 600)
plot(CorrbetweenOLDSoANEWandsoo)
dev.off()

tidy(cor.test(questionnaire$Performance, questionnaire$SoO, method="spearman", exact = FALSE))
CorrbetweenSoOandperf <- ggplot(questionnaire,aes(x=Performance,y=SoO, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Embodiment") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("CorrbetweenSoOandperf.png", width = 800, height = 600)
plot(CorrbetweenSoOandperf)
dev.off()

tidy(cor.test(questionnaire$Performance, questionnaire$Frustration, method="spearman", exact = FALSE))
Corrbetweenfrustandperf <- ggplot(questionnaire,aes(x=Performance,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("Corrbetweenfrustandperf.png", width = 800, height = 600)
plot(Corrbetweenfrustandperf)
dev.off()

tidy(cor.test(questionnaire$SoANEW, questionnaire$Frustration, method="spearman", exact = FALSE))
CorrbetweenSoANEWandfrust <- ggplot(questionnaire,aes(x=SoANEW,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "New agency measure") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("CorrbetweenSoANEWandfrust.png", width = 800, height = 600)
plot(CorrbetweenSoANEWandfrust)
dev.off()

tidy(cor.test(questionnaire$Performance, questionnaire$Proprioception, method="spearman", exact = FALSE))
CorrbetweenSoOandproprio <- ggplot(questionnaire,aes(x=Performance,y=Proprioception, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 5) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Proprioception") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_bw(base_size = 25)+
  geom_smooth(method = "lm", fill = NA)
png("CorrbetweenSoOandproprio.png", width = 800, height = 600)
plot(CorrbetweenSoOandproprio)
dev.off()

#correlation test on frustration
tidy(cor.test(dfData$SoO, dfData$Frustration, method="spearman", exact = FALSE))
SoOFruScatter <- ggplot(dfData,aes(x=SoO,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoO") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)

#correlation test on Proprioception
tidy(cor.test(dfData$SoO, dfData$Proprioception, method="spearman", exact = FALSE))
SoOPropioScatter <- ggplot(dfData,aes(x=SoO,y=Proprioception, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoO") +
  ylab(label = "Proprioception") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)

#Saving Plots
png("SoOSoANEWScatter.png", width = 800, height = 600)
plot(SoOSoANEWScatter)
dev.off()
png("SoOFruScatter.png", width = 800, height = 600)
plot(SoOFruScatter)
dev.off()
png("SoOPropioScatter.png", width = 800, height = 600)
plot(SoOPropioScatter)
dev.off
```

```{r Correlation test for SoANEW, Frustration and Proprioception}
#correlation test on Frustration
tidy(cor.test(dfData$SoANEW, dfData$Frustration, method="spearman", exact = FALSE))
SoANEWFRuScatter <- ggplot(dfData,aes(x=SoANEW,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoANEW") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)


#correlation test on Proprioception
tidy(cor.test(dfData$SoANEW, dfData$Proprioception, method="spearman", exact = FALSE))
SoANEWPropioScatter <- ggplot(dfData,aes(x=SoANEW,y=Proprioception, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "SoANEW") +
  ylab(label = "Proprioception") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)

#correlation test on Proprioception and Frustration
tidy(cor.test(dfData$Proprioception, dfData$Frustration, method="spearman", exact = FALSE))
ProprioFruScatter <- ggplot(dfData,aes(x=Proprioception,y=Frustration, colour=Level, fill=Level))+ 
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Proprioception") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)

#correlation test on perf and old SoANEW
tidy(cor.test(questionnaire$SoAOLD, questionnaire$Performance, method="spearman", exact = FALSE))
SoAOLDperformanceScatter <- ggplot(questionnaire,aes(x=SoAOLD,y=Performance, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Old agency question") +
  ylab(label = "Performance") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("SoAOLDperformanceScatter.png", width = 800, height = 600)
plot(SoAOLDperformanceScatter)
dev.off()

#correlation test on perf and old SoANEW
tidy(cor.test(questionnaire$SoANEW, questionnaire$Performance, method="spearman", exact = FALSE))
SoANEWperformanceScatter <- ggplot(questionnaire,aes(x=SoAOLD,y=Performance, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "New agency question") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("SoANEWperformanceScatter.png", width = 800, height = 600)
plot(SoANEWperformanceScatter)
dev.off()

tidy(cor.test(questionnaire$Performance, questionnaire$SoANEW, method="spearman", exact = FALSE))
SoANEWperformanceScatter <- ggplot(questionnaire,aes(x=Performance,y=SoANEW, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "new agency question") +
  ylab(label = "Performance") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("SoANEWperformanceScatter.png", width = 800, height = 600)
plot(SoANEWperformanceScatter)
dev.off()

tidy(cor.test(questionnaire$Frustration, questionnaire$Performance, method="spearman", exact = FALSE))
FrustrationperformanceScatter <- ggplot(questionnaire,aes(x=Performance,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("FrustrationperformanceScatter.png", width = 800, height = 600)
plot(FrustrationperformanceScatter)
dev.off()

tidy(cor.test(questionnaire$Frustration, questionnaire$SoO, method="spearman", exact = FALSE))
FrustrationSoOScatter <- ggplot(questionnaire,aes(x=SoO,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Embodiment") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("FrustrationSoOScatter.png", width = 800, height = 600)
plot(FrustrationSoOScatter)
dev.off()


#correlation test on perf and old SoANEW
tidy(cor.test(questionnaire$SoANEW, questionnaire$SoAOLD, method="spearman", exact = FALSE))
SoANEWandoldScatter <- ggplot(questionnaire,aes(x=SoAOLD,y=SoANEW))+
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "new agency question") +
  ylab(label = "old agency question") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
png("SoANEWandoldScatter.png", width = 800, height = 600)
plot(SoANEWandoldScatter)
dev.off()

#Saving Plots
png("SoANEWFRuScatter.png", width = 800, height = 600)
plot(SoANEWFRuScatter)
dev.off()
png("SoANEWPropioScatter.png", width = 800, height = 600)
plot(SoANEWPropioScatter)
dev.off()
png("ProprioFruScatter.png", width = 800, height = 600)
plot(ProprioFruScatter)
dev.off
```

```{r Correlation test for Performance on SoO, SoANEW, Frustration and Proprioception}
#correlation test on SoO
tidy(cor.test(dfData$Performance, dfData$SoO, method="spearman", exact = FALSE))
PerfSoOScatter <- ggplot(dfData,aes(x=Performance,y=SoO, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(0,1), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "SoO") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)

#correlation test on SoANEW
tidy(cor.test(dfData$Performance, dfData$SoANEW, method="spearman", exact = FALSE))
PerfSoANEWScatter <- ggplot(dfData,aes(x=Performance,y=SoANEW, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(0,1), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "SoANEW") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
#correlation test on Frustration
tidy(cor.test(dfData$Performance, dfData$Frustration, method="spearman", exact = FALSE))
PerfFruScatter <- ggplot(dfData,aes(x=Performance,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(0,1), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
#correlation test on Proprioception
tidy(cor.test(dfData$Performance, dfData$Proprioception, method="spearman", exact = FALSE))
PerfProprioScatter <- ggplot(dfData,aes(x=Performance,y=Proprioception, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(0,1), y=c(1, 7))+
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  xlab(label = "Performance") +
  ylab(label = "Proprioception") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
#Saving Plots
png("PerfSoOScatter.png", width = 800, height = 600)
plot(PerfSoOScatter)
dev.off()
png("PerfSoANEWScatter.png", width = 800, height = 600)
plot(PerfSoANEWScatter)
dev.off()
png("PerfFruScatter.png", width = 800, height = 600)
plot(PerfFruScatter)
dev.off
png("PerfProprioScatter.png", width = 800, height = 600)
plot(PerfProprioScatter)
dev.off()
```

```{r Correlation test for Performance on SoANEW using orderNumber}
#correlation test on SoANEW order 1
tidy(cor.test(ParticipantOrder1$Performance, ParticipantOrder1$SoANEW, method="spearman", exact = FALSE))
ggplot(ParticipantOrder1,aes(x=Performance,y=SoANEW, colour=Level))+ geom_point() + expand_limits(x=c(0,1), y=c(1, 7)) + geom_smooth(method = "lm", fill = NA)
ggplot(dfSummary,aes(x=Performance,y=SoANEW, colour=Level))+ geom_jitter(width = .1,height = .1) + expand_limits(x=c(0,1), y=c(1, 7)) + geom_smooth(method = "lm", fill = NA)+theme_bw()
#correlation test on SoANEW order 2
tidy(cor.test(ParticipantOrder2$Performance, ParticipantOrder2$SoANEW, method="spearman", exact = FALSE))
ggplot(ParticipantOrder2,aes(x=Performance,y=SoANEW, colour=Level))+ geom_point() + expand_limits(x=c(0,1), y=c(1, 7)) + geom_smooth(method = "lm", fill = NA)
```

```{r Present results}
#This chunk is for all the missing data and graphs for the results sections
MBlocks <- dfData %>% filter(Level=="Blocks")
MAvatar <- dfData %>% filter(Level=="Avatar")

#Median: I manually changed X
median(MBlocks$Proprioception , trim = 0, na.rm = FALSE)
median(MAvatar$Proprioception , trim = 0, na.rm = FALSE)

#Performance
  #boxplot
PerformanceBoxplot <- ggplot(dfData, aes(Performance, y=Level, fill=Level)) + 
  coord_flip() + 
  scale_fill_manual(values=c("red","blue"))+
  ylab(label = "Level") +
  xlab(label = "Performance(%)") +
  labs(fill = "Conditions", colour = "Conditions")+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)
  #Histogram
PerformanceHisto <- ggplot(dfData,aes(Performance, fill=Level))+
   scale_fill_manual(values=c("red","blue"))+
   xlab(label = "Performance") +
   ylab(label = "Fequency") +
   labs(fill = "Conditions", colour = "Conditions")+
   geom_histogram(alpha=0.5,bins=50,position="identity")

#SoO
  #Histogram
SoOHisto <- ggplot(dfData,aes(SoO, fill=Level),xlab=7,ylab=7)+
   scale_fill_manual(values=c("red","blue"))+
   xlab(label = "SoO") +
   ylab(label = "Fequency") +
   labs(fill = "Conditions", colour = "Conditions")+
   geom_histogram(alpha=0.5,bins=14,position="identity")
  #boxplot
SoOBoxplot <- ggplot(dfData, aes(SoO, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "SoO") +
  ylab(label = "Level") +
  scale_fill_manual(values=c("red","blue"))+
  labs(fill = "Conditions", colour = "Conditions")+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)

#SoANEW
  #Histogram
SoANEWHisto <- ggplot(dfData,aes(SoANEW, fill=Level),xlab=7,ylab=7)+
   scale_fill_manual(values=c("red","blue"))+
   xlab(label = "SoANEW") +
   ylab(label = "Fequency") +
   labs(fill = "Conditions", colour = "Conditions")+
   geom_histogram(alpha=0.5,bins=14,position="identity")
  #boxplot
SoANEWBoxplot <- ggplot(dfData, aes(SoANEW, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "SoANEW") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("red","blue"))+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)

  #boxplot
newSoANEWBoxplot <- ggplot(questionnaire, aes(questionnaire$SoANEW, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "New agency question") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("red","blue"))+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)
png("newSoANEWBoxplot.png", width = 800, height = 600)
plot(newSoANEWBoxplot)
dev.off()
  #boxplot
oldSoANEWBoxplot <- ggplot(questionnaire, aes(questionnaire$SoAOLD, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "Old agency question") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("red","blue"))+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)
png("oldSoANEWBoxplot.png", width = 800, height = 600)
plot(oldSoANEWBoxplot)
dev.off()

#Frustation
  #Histogram
FrustationHisto <- ggplot(dfData,aes(Frustration, fill=Level),xlab=7,ylab=7)+
   scale_fill_manual(values=c("red","blue"))+
   xlab(label = "Frustration") +
   ylab(label = "Fequency") +
   labs(fill = "Conditions", colour = "Conditions")+
   geom_histogram(alpha=0.5,bins=14,position="identity")
  #boxplot
FrustationBoxplot <- ggplot(dfData, aes(Frustration, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "Frustration") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("red","blue"))+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)

#Proprioception 
  #Histogram
ProprioceptionHisto <- ggplot(dfData,aes(Proprioception , fill=Level),xlab=7,ylab=7)+
   scale_fill_manual(values=c("red","blue"))+
   xlab(label = "Proprioception ") +
   ylab(label = "Fequency") +
   labs(fill = "Conditions", colour = "Conditions")+
   geom_histogram(alpha=0.5,bins=14,position="identity")
  #boxplot
ProprioceptionBoxplot <- ggplot(dfData, aes(Proprioception , y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "Proprioception ") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("red","blue"))+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)

 #save plots (Does not work yet)

 # vector1 <- c(PerformanceBoxplot,PerformanceHisto,SoOHisto)
 # 
 # for ( i in seq_along(vector1)) {
 #   png(i+".png", width = 800, height = 600)
 #   plot(i)
 #   dev.off()
 # }

png("PerformanceBoxplot.png", width = 800, height = 600)
plot(PerformanceBoxplot)
dev.off()
png("PerformanceHisto.png", width = 800, height = 600)
plot(PerformanceHisto)
dev.off()
png("SoOHisto.png", width = 800, height = 600)
plot(SoOHisto)
dev.off()
png("SoOBoxplot.png", width = 800, height = 600)
plot(SoOBoxplot)
dev.off()
png("SoANEWHisto.png", width = 800, height = 600)
plot(SoANEWHisto)
dev.off()
png("SoANEWBoxplot.png", width = 800, height = 600)
plot(SoOBoxplot)
dev.off()
png("FrustationHsto.png", width = 800, height = 600)
plot(FrustationHisto)
dev.off()
png("FrustationBoxplot.png", width = 800, height = 600)
plot(FrustationBoxplot)
dev.off()


```

```{r AV results}
#This chunk is for all the missing data and graphs for the results sections
#SoO + SoANEW
AVSoOSoANEWScatterplot <- ggplot(dfData,aes(x=SoO,y=SoANEW, colour=Level, fill=Level))+ 
  geom_point(position=position_jitter(h=0.08, w=0.08), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("#E66100","#5D3A9B")) +
  scale_fill_manual(values=c("#E66100","#5D3A9B")) +
  xlab(label = "SoO") +
  ylab(label = "SoANEW") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_minimal()+
  geom_smooth(method = "lm", fill = NA)
#performance + frustration
AVperformanceFrustrationScatterplot <- ggplot(dfData,aes(x=Performance,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(0,1), y=c(1, 7))+
  scale_color_manual(values=c("#E66100","#5D3A9B")) +
  scale_fill_manual(values=c("#E66100","#5D3A9B")) +
  xlab(label = "Performance") +
  ylab(label = "Frustration") +
  theme_minimal()+
  labs(fill = "Conditions", colour = "Conditions")+
  geom_smooth(method = "lm", fill = NA)
#SoANEW + frustration
AVSoANEWFrustrationScatterplot <- ggplot(dfData,aes(x=SoANEW,y=Frustration, colour=Level, fill=Level))+
  geom_point(position=position_jitter(h=0.1, w=0.0), shape = 21, alpha = 0.5, size = 3) +
  expand_limits(x=c(1,7), y=c(1, 7))+
  scale_color_manual(values=c("#E66100","#5D3A9B")) +
  scale_fill_manual(values=c("#E66100","#5D3A9B")) +
  xlab(label = "SoANEW") +
  ylab(label = "Frustration") +
  labs(fill = "Conditions", colour = "Conditions")+
  theme_minimal()+
  geom_smooth(method = "lm", fill = NA)

AVSoOBoxplot<- ggplot(dfData, aes(SoO, y=Level, fill=Level)) + 
  coord_flip() + 
  xlab(label = "SoO") +
  ylab(label = "Level") +
  labs(fill = "Conditions", colour = "Conditions")+
  scale_fill_manual(values=c("#E66100","#5D3A9B"))+
  theme_minimal()+
  geom_boxplot(outlier.colour="red", outlier.shape=8,outlier.size=4, alpha=0.5)


png("AVSoOSoANEWScatterplot.png", width = 800, height = 600)
plot(AVSoOSoANEWScatterplot)
dev.off()
png("AVperformanceFrustrationScatterplot.png", width = 800, height = 600)
plot(AVperformanceFrustrationScatterplot)
dev.off()
png("AVSoANEWFrustrationScatterplot.png", width = 800, height = 600)
plot(AVSoANEWFrustrationScatterplot)
dev.off()
png("AVSoOBoxplot.png", width = 800, height = 600)
plot(AVSoOBoxplot)
dev.off()

```
```{r Wilconson Singed Ranked test ON SoO, SoANEW, Frustration and Proprioception }


wilcox.test(dfAvatar$SoO, dfBlocks$SoO, paired=TRUE,exact=FALSE)
wilcox.test(dfAvatar$SoANEW, dfBlocks$SoANEW, paired=TRUE,exact=FALSE)
wilcox.test(dfAvatar$Frustration, dfBlocks$Frustration, paired=TRUE,exact=FALSE)
wilcox.test(dfAvatar$Proprioception, dfBlocks$Proprioception, paired=TRUE,exact=FALSE)
wilcox.test(questionnaire$SoANEW, questionnaire$SoAOLD, paired = TRUE, exact = FALSE)

wilcox.test(dfAvatar$SoANEW, dfBlocks$SoANEW, paired=TRUE,exact=FALSE)
wilcox.test(dfAvatar$SoAOLD, dfBlocks$SoAOLD, paired=TRUE,exact=FALSE)

wilcox.test(dfAvatar$Frustration, dfBlocks$Frustration, paired=TRUE,exact=FALSE)

```

```{r SoO compact plot}
ID <- 1:7
gg2 <- summarySE(questionnaire, measurevar="SoO", groupvars =c( "Level"))

SoOCompactPlot <- ggplot(gg2, aes(Level, SoO, colour=Level)) + 
  theme_classic(base_size = 30) +
  geom_boxplot(aes(lower = SoO - ci, upper = SoO + ci, middle = SoO, ymin = SoO - 3*ci, ymax = SoO + 3*ci),
    stat = "identity", color="#454545", width=.5, alpha=0) +
  geom_beeswarm(data = questionnaire, priority='density',cex=3, color="gray", aes(size=3, stroke=1)) + geom_line(data = questionnaire,aes(group=Participant))+
  scale_x_discrete(limits=c(), labels=c("Blocks", "Avatar")) +
  scale_y_continuous("ownership", limits=c(1, 7.5), labels = as.character(ID), breaks = ID) +
  ylab("SoO Scores") + xlab("") + theme(legend.position="none")

SoOBuildData <- ggplot_build(SoOCompactPlot)$data[[1]]
# Add red mean median lines
SoOCompactPlot2 <- SoOCompactPlot + geom_segment(data=SoOBuildData, aes(x=xmin, xend=xmax, y=middle, yend=middle), colour="red", size=2)

png("SoOCompactPlot.png", width = 800, height = 600)
plot(SoOCompactPlot2)
dev.off()

summary(lm(SoANEW~SoO+factor(Level)*Performance,dfSummary))

```
# ```{r SoANEW compact plot}
# # ID <- 1:7
# # gg3 <- summarySE(questionnaire, measurevar="SoANEW", groupvars =c( "Level"))
# # 
# # SoANEWCompactPlot <- ggplot(gg3, aes(Level, SoANEW, colour=Level)) + 
# #   theme_classic(base_size = 30) +
# #   geom_boxplot(aes(lower = SoANEW - ci, upper = SoANEW + ci, middle = SoANEW, ymin = SoANEW - 3*ci, ymax = SoANEW + 3*ci),
# #     stat = "identity", color="#454545", width=.5, alpha=0) +
# #   geom_beeswarm(data = questionnaire, priority='density',cex=3, color="gray", aes(size=3, stroke=1)) + geom_line(data = questionnaire,aes(group=Participant))+
# #   scale_x_discrete(limits=c(), labels=c("Blocks", "Avatar")) +
# #   scale_y_continuous("SoANEW", limits=c(1, 7.5), labels = as.character(ID), breaks = ID) +
# #   ylab("NEW SoANEW Scores") + xlab("") + theme(legend.position="none")
# # 
# # SoANEWCompactPdata <- ggplot_build(SoANEWCompactPlot)$data[[1]]
# # # Add red mean median lines
# # SoANEWCompactPlot2 <- SoANEWCompactPlot + geom_segment(data=SoANEWCompactPdata, aes(x=xmin, xend=xmax, y=middle, yend=middle), colour="red", size=2)
# # 
# # png("SoANEWCompactPlot.png", width = 800, height = 600)
# # plot(SoANEWCompactPlot2)
# # dev.off()
# ```

```{r SoAOLD compact plot}
ID <- 1:7
gg4 <- summarySE(questionnaire, measurevar="SoAOLD", groupvars =c( "Level"))

SoAOLDCompactPlot <- ggplot(gg4, aes(Level, SoAOLD, colour=Level)) + 
  theme_classic(base_size = 30) +
  geom_boxplot(aes(lower = SoAOLD - ci, upper = SoAOLD + ci, middle = SoAOLD, ymin = SoAOLD - 3*ci, ymax = SoAOLD + 3*ci),
    stat = "identity", color="#454545", width=.5, alpha=0) +
  geom_beeswarm(data = questionnaire, priority='density',cex=3, color="gray", aes(size=3, stroke=1)) + geom_line(data = questionnaire,aes(group=Participant))+
  scale_x_discrete(limits=c(), labels=c("Blocks", "Avatar")) +
  scale_y_continuous("SoAOLD", limits=c(1, 7.5), labels = as.character(ID), breaks = ID) +
  ylab("OLD SoANEW Scores") + xlab("") + theme(legend.position="none")

SoAOLDCompactPdata <- ggplot_build(SoAOLDCompactPlot)$data[[1]]
# Add red mean median lines
SoAOLDCompactPlot2 <- SoAOLDCompactPlot + geom_segment(data=SoAOLDCompactPdata, aes(x=xmin, xend=xmax, y=middle, yend=middle), colour="red", size=2)

png("SoAOLDCompactPlot.png", width = 800, height = 600)
plot(SoAOLDCompactPlot2)
dev.off()

```

```{r SoANEW compact plot}
# gg2 <- summarySE(dfData, measurevar="SoANEW", groupvars =c( "Level"))
# 
# SoANEWCompactPlot <- ggplot(gg2, aes(Level, SoANEW, colour=Level)) + 
#   theme_classic(base_size = 30) +
#   geom_boxplot(aes(lower = SoANEW - ci, upper = SoANEW + ci, middle = SoANEW, ymin = SoANEW - 3*ci, ymax = SoANEW + 3*ci),
#     stat = "identity", color="#454545", width=.5, alpha=0) +
#   geom_beeswarm(data = dfData, priority='density',cex=3, color="gray", aes(size=3, stroke=1)) +
#   scale_x_discrete(limits=c(), labels=c("Blocks", "Avatar")) +
#   scale_y_continuous("agency", limits=c(1, 7.5), labels = as.character(ID), breaks = ID) +
#   ylab("SoANEW Scores") + xlab("") + theme(legend.position="none")
# 
# SoANEWBuildData <- ggplot_build(SoANEWCompactPlot)$data[[1]]
# # Add red mean median lines
# SoANEWCompactPlot2 <- SoANEWCompactPlot + geom_segment(data=SoANEWBuildData, aes(x=xmin, xend=xmax, y=middle, yend=middle), colour="red", size=2)
# 
# png("SoANEWCompactPlot.png", width = 800, height = 600)
# plot(SoANEWCompactPlot2)
# dev.off()


```

```{r Performance compact plot}
gg2 <- summarySE(dfData, measurevar="Performance", groupvars =c( "Level"))
PerformanceCompactPlot <- ggplot(gg2, aes(Level, Performance, colour=Level)) + theme_bw(base_size = 25) +
  geom_jitter(data = dfData, aes(Level, Performance), width=0.2, color="black", alpha=0.5, size=3) + 
  geom_point(position=position_dodge(0.2), size=4, colour="red") +
  geom_errorbar(aes(ymin=Performance-ci, ymax=Performance+ci), width=.4, position = position_dodge(0.2), color=c("red", "blue")) +
  scale_x_discrete(limits=c(), labels=c("Blocks", "Avatar")) +
  scale_y_continuous(limits = c(0,30)) +
  ylab("Performance(%)") + xlab("") + theme(legend.position="none")

png("Performance.png", width = 800, height = 600)
plot(PerformanceCompactPlot)
dev.off()


```
```{r HK additional analysis for main effects compact plot}
library(scatterplot3d)
dfSummary$ownership <-dfSummary$SoO
fit.OPerf <- lm(formula = SoANEW ~ Performance + SoO , data = dfSummary)
pd<-dfSummary %>% select(Performance ,SoO, SoANEW,Level)
pd.aug<-lions.augmented <- augment(fit.OPerf, pd)

p <- scatterplot3d(y=pd$SoO, z=pd$SoANEW, x=pd$Performance,angle=55,type='h',
                   pch = 16, color = "steelblue")
plot.new()
# add a plane representing the fit of the model
p$plane3d(fit.OPerf, col='orangered')

ggplot(pd.aug, aes(SoANEW, .resid)) + 
    geom_point() + geom_smooth(method="lm", color="red",se=FALSE) +
    geom_segment(aes(xend = SoANEW, yend = .fitted), linetype="dashed")

ggplot(pd.aug, aes(Performance, .resid)) + 
  geom_point() + 
  geom_hline(yintercept = 0, color = "red", linetype='dashed') + 
  labs(y = "Residuals", title = "Residual plot of the regression model.")

mypalette <- c("firebrick", "royalblue") 
sp <- scatterplot3d::scatterplot3d(y=pd$SoO,
                                   z=pd$SoANEW,
                                   x=pd$Performance,
                                   angle = 45,
                                   # col = mypalette[as.numeric(as.factor(pd$Level))],
                                   xlab="performance", ylab="ownership", zlab="agency")
plot.new()
sp$plane3d(fit.OPerf, lty.box = "solid")#,
           # polygon_args = list(col = rgb(.1, .2, .7, .5)) # Fill color

ggplot(dfSummary,aes(x=SoO,y=SoANEW,size=Performance))+geom_point()

orig <- sp$xyz.convert(y=pd$SoO,
                       z=pd$SoANEW,
                       x=pd$Performance)
plane <- sp$xyz.convert(pd$Performance,
                        pd$SoO,
                        fitted(fit.OPerf))
i.negpos <- 1 + (resid(fit.OPerf) > 0)
segments(orig$x, orig$y, plane$x, plane$y,
         col = c("blue", "red")[i.negpos],
         lty = 1) # (2:1)[i.negpos]
sp <- FactoClass::addgrids3d(y=pd$SoO,
                             z=pd$SoANEW,
                             x=pd$Performance,
                             angle = 55)



ggplot(dfSummary,aes(size=ownership,y=SoANEW,x=Performance/30))+geom_jitter(hight=.2,alpha=.5)+theme_bw()+ylab('agency')+xlab('performance (percentage of popped balloons)')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE)+scale_y_continuous(breaks=seq(1,7,1))+theme_bw()+  scale_x_continuous( labels = scales::percent,limits = c(0, 1))+
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())

AP<- ggplot(dfSummary,aes(size=ownership,y=SoANEW,x=Performance,colour=Level,group=Level))+geom_jitter(height=.2,alpha=.5)+theme_bw()+ylab('perceived agency')+xlab('performance (number of popped balloons)')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE, se=FALSE)+scale_y_continuous(breaks=seq(1,7,1))+scale_x_continuous(breaks=seq(0,31,5))+theme_bw()+
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())

AO<- ggplot(dfSummary,aes(x=ownership,y=SoANEW,size=Performance,colour=Level,group=Level))+geom_jitter(width=.3,height=.3,alpha=.5)+ylab('agency')+xlab('ownership')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE, se=FALSE)+scale_y_continuous(breaks=seq(1,7,1))+scale_x_continuous(breaks=seq(1,7,1))+theme_bw()+   
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())

dfSummary %>% select(Participant, Performance) %>% group_by(Participant) %>% dplyr::mutate(n=1:n())%>% pivot_wider(names_from=n,values_from=Performance) %>% mutate(diff=`1`-`2`) %>% View()

 dfSummary %>% select(Participant, Level, Performance) %>% mutate(Performance=Performance/30) %>% ggplot(aes(x=Performance,group=Level))+geom_density()

 library(ggpubr)

 ggarrange(AO, AP , 
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
 
# create plot with trendline from predictions of both parameters
modOLxP <- lm(SoANEW~SoO+Level*Performance,data=dfSummary)
dfSummary<- dfSummary %>%  add_predictions(modOLxP) 



 ggplot(dfSummary,aes(x=Performance,y=SoANEW,size=ownership,colour=Level,group=Level))+geom_jitter(width=.3,height=.3,alpha=.5)+ylab('agency')+xlab('performance')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE, se=FALSE)+scale_y_continuous(breaks=seq(1,7,1))+scale_x_continuous(breaks=seq(0,30,5))+theme_bw()
 
  ggplot(dfSummary,aes(x=SoO,y=SoANEW,size=SoO))+geom_jitter(width=.3,height=.3,alpha=.5)+ylab('agency')+xlab('performance')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE, se=FALSE)+scale_y_continuous(breaks=seq(1,7,1))+scale_x_continuous(breaks=seq(1,7,1))+theme_bw()
 
  dfSummary$LevXPerf <- as.numeric(as.factor(dfSummary$Level)) * dfSummary$Performance

  dfSummary %>% 
    mutate(embodiment=factor(Level, levels = c("Body","Blocks"))) %>%
    mutate(embodiment= recode_factor(embodiment, Body = "Avatar hand")) %>%
  ggplot(aes(size=ownership,y=SoANEW,x=Performance,colour=embodiment,group=embodiment))+geom_jitter(height=.2,alpha=.5)+theme_bw()+ylab('perceived agency')+xlab('MI-BCI performance (number of popped balloons)')+geom_smooth(method='lm', formula= y~x,show.legend = FALSE, se=FALSE)+scale_y_continuous(breaks=seq(1,7,1))+scale_x_continuous(breaks=seq(0,31,5))+theme_bw()
  
  
  #SEM model structural equation modelling
  m4<- 'SoO ~ 1 + Level
    SoANEW ~ 1+  SoO + Performance 
    Frustration ~ 1  + Performance + SoANEW 
  '
  fitm4<-lavaan::sem(m4,data=dfSummary)
  summary(fitm4)
  modificationindices(fitm4)
  fitm4
  library(lavaan)
  library(tidySEM)
  graph_sem(model = fitm4)
  
  prepare_graph(fitm4) %>%
  color_pos_edges("green") %>%
  color_neg_edges("red") %>%
  color_var("black") %>%
  alpha_var(.2) %>%
  plot()
  
```
